parameters:
    mesd_crud_history_app_name: %app_name%

services:
#    mesd_crud_history.example:
#        class: %mesd_crud_history.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my.listener:
        class: Mesd\CrudHistoryBundle\Listener\CrudLogListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        arguments:
            container: @service_container