<?php

namespace Mesd\CrudHistoryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CrudHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrudHistoryRepository extends EntityRepository
{
}
